name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r model/requirements.txt

    - name: Run training script
      run: |
        python model/train.py

    - name: Upload model to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: car-price-model
        path: model/car_price_model.pth

